# Lab 3: Comparisons, Tables

## Part I: Comparisons

### a. Compare numbers

In [1]:
2<=3

True

In [2]:
4!=4

False

In [3]:
3<4<5-3

False

In [4]:
3<4<5*3

True

In [5]:
# Note: Differences between = and == !
a=3
a=2
a

2

In [6]:
a=3
a==2

False

In [7]:
3=2

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (642450305.py, line 1)

### b. Compare strings

In [8]:
# try a)
'apple' < 'banana'

True

In [9]:
# try b)
'cab' < 'car'

True

In [10]:
# try c)
'car' < 'cartwheel'

True

### c. Compare arrays

In [11]:
from datascience import *

a = make_array(1, 3, 5)
b = make_array(2, 3, 4)

a < b

array([ True, False, False], dtype=bool)

## Part 2: Importing Data into a Table

In [12]:
from datascience import * # do not forget this command!

### Problem 1

In [13]:
# a) 
listings = Table.read_table("https://data.insideairbnb.com/united-states/hi/hawaii/2025-06-13/visualisations/listings.csv")

In [14]:
listings

id      | name                                              | host_id   | host_name | neighbourhood_group | neighbourhood | latitude | longitude | room_type       | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 | number_of_reviews_ltm | license
1371734 | Waipouli Beach Resort G305                        | 756093    | Kaua’i    | Kauai               | Kapaa-Wailua  | 22.0623  | -159.319  | Entire home/apt | 462   | 3              | 39                | 2025-03-04  | 0.29              | 66                             | 307              | 7                     | 430080010161
1931754 | Hana Ocean Palms Bungalow           STHA2009-003  | 7877427   | Albert    | Maui                | Hana          | 20.6824  | -156.03   | Entire home/apt | 442   | 2              | 214               | 2025-06-30  | 1.94              | 1                              | 231              | 30                    | 140120140000, TA-154-921-5744-01
3478308 | Direct Ocean Views! $99 Summer Specials! Sunsets! | 17519759  | Lonelle   | Maui                | Lahaina       | 20.9587  | -156.684  | Entire home/apt | 111   | 1              | 171               | 2025-05-27  | 1.31              | 13                             | 295              | 6                     | 430060440051, TA-045-342-5152-01
3489488 | Paradise found                                    | 17571531  | Dorothy   | Maui                | Molokai       | 21.1899  | -157.245  | Entire home/apt | 124   | 2              | 2                 | 2024-07-21  | 0.15              | 1                              | 360              | 1                     | 510030060106, TA-022-751-6416-01
87596   | Garden Suite at Onomea                            | 479545    | Randall   | Hawaii              | South Hilo    | 19.8148  | -155.103  | Entire home/apt | 120   | 2              | 346               | 2025-06-03  | 2.03              | 2                              | 254              | 43                    | TA 095-813-2224-01  /  GE 095-813-2224-01
430961  | 1B Maui Vista Condo w/ Beach Access               | 224701170 | Deb       | Maui                | Kihei-Makena  | 20.7245  | -156.447  | Entire home/apt | 145   | 7              | 191               | 2025-05-06  | 1.2               | 2                              | 267              | 19                    | 390180030211, TA-094-736-1792-01
440924  | Fabulous 3 Bedrm Poipu Beach CONDO #122           | 483893    | Pamela    | Kauai               | Koloa-Poipu   | 21.8743  | -159.447  | Entire home/apt | 435   | 5              | 177               | 2025-06-11  | 1.13              | 2                              | 251              | 17                    | 280270200008
444403  | Amazing Oceanfront with Back Yard- Kona, Hawaii!  | 1516971   | Sandy     | Hawaii              | North Kona    | 19.5731  | -155.967  | Entire home/apt | 211   | 4              | 18                | 2024-11-05  | 0.11              | 4                              | 34               | 6                     | STVR 19-358769
455874  | Garden Room Studio                                | 1995357   | Dean      | Hawaii              | North Kona    | 19.638   | -155.986  | Entire home/apt | 131   | 3              | 111               | 2024-11-09  | 0.73              | 4                              | 195              | 2                     | TA-193-891-1232-01
461418  | Lotus Garden/Lotus Cottage Downtown 3BR           | 2128914   | Megan     | Hawaii              | South Hilo    | 19.7225  | -155.086  | Entire home/apt | 209   | 1              | 245               | 2025-04-28  | 1.59              | 5                              | 180              | 6                     | W85296321-01
... (36442 rows omitted)

In [ ]:
# b)
# download and move the students.txt into the directory first!
students = Table.read_table("students.txt", names = ["Name", "Age", "Gender"], delimiter = " ")
students

In [16]:
# Tips: show method
listings.show(3)

In [ ]:
students.show()

In [ ]:
# Tips: num_rows & num_columns method


# students.num_rows
students.num_columns

## Part 3: Manipulating Data in a Table

### Sorting data

In [19]:
# table_name.sort(column_or_label) --> in an ascending order by default
# table_name.sort(column_or_label, descending = True) --> in a descending order

# Option 1: 
listings.sort(0)

id    | name                                               | host_id | host_name  | neighbourhood_group | neighbourhood     | latitude | longitude | room_type       | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 | number_of_reviews_ltm | license
5269  | Upcountry Hospitality in the 'Auwai Suite          | 7620    | Lea & Pat  | Hawaii              | South Kohala      | 20.0274  | -155.702  | Entire home/apt | 141   | 3              | 44                | 2025-06-13  | 0.26              | 3                              | 293              | 8                     | 119-269-5808-01R
5387  | Hale Koa Studio & 1 Bedroom Units!!                | 7878    | Edward     | Hawaii              | South Kona        | 19.4308  | -155.881  | Entire home/apt | 90    | 5              | 233               | 2025-04-30  | 1.25              | 2                              | 259              | 11                    | TA-163-133-0304-01
5480  | Isle Of You Naturally Farm Retreat                 | 8145    | Normand    | Hawaii              | Puna              | 19.4415  | -154.915  | Private room    | 117   | 2              | 0                 | nan         | nan               | 3                              | 365              | 0                     | nan
5532  | 2BR Waialua Beach Condo w/ Saltwater Pool & Sauna  | 8279    | Sarada     | Honolulu            | North Shore Oahu  | 21.5822  | -158.136  | Entire home/apt | nan   | 7              | 0                 | nan         | nan               | 1                              | 0                | 0                     | nan
7888  | Pineapple House 2 Bed 1 Bath with Loft Entire Home | 22083   | Steven     | Hawaii              | Puna              | 19.5123  | -154.91   | Entire home/apt | 98    | 1              | 128               | 2017-05-21  | 0.7               | 1                              | 157              | 0                     | GE-104-390-7584-01
7896  | Maui Sunset Condo Beachfront Resort, Kihei/Wailea  | 21844   | Caroline   | Maui                | Kihei-Makena      | 20.7568  | -156.456  | Entire home/apt | 168   | 4              | 95                | 2025-04-23  | 0.53              | 1                              | 319              | 17                    | 390010020007, TA-169-914-3680-01
13238 | Studio On Princeville Golf Course / Paniolo Condo  | 51647   | Annie/Greg | Kauai               | North Shore Kauai | 22.2184  | -159.471  | Entire home/apt | 152   | 3              | 189               | 2025-05-31  | 1.42              | 2                              | 267              | 12                    | 540050030025, TA-095-127-9616-01
13523 | All Inclusive that has it all, Sleeps 8, Hot Tub   | 52931   | Mark       | Honolulu            | Koolaupoko        | 21.3412  | -157.702  | Entire home/apt | 350   | 30             | 36                | 2023-11-10  | 0.35              | 8                              | 344              | 0                     | 410070800000, 0000, Ta-002-351-5136-01
13528 | 2BR Pacific Shores by the Beach                    | 52969   | Lisa       | Maui                | Kihei-Makena      | 20.7241  | -156.448  | Entire home/apt | 275   | 1              | 264               | 2024-01-29  | 1.41              | 1                              | 182              | 0                     | 390180020064, TA-103-659-7248-01
13688 | Oceanfront Bali House w/ Hot tub @ Kehena Beach    | 53657   | Janet Lynn | Hawaii              | Puna              | 19.394   | -154.931  | Entire home/apt | 278   | 3              | 183               | 2025-06-08  | 1                 | 4                              | 217              | 10                    | TAGE 176-619-3665-01
... (36442 rows omitted)

In [20]:
# Option 2: 
listings.sort("host_id", descending = True)

id                  | name                                               | host_id   | host_name                     | neighbourhood_group | neighbourhood        | latitude | longitude | room_type       | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 | number_of_reviews_ltm | license
971799951323936988  | Ocean View Villa in Kahana, Maui - 2BD/2BA         | 703819949 | Josefina                      | Maui                | Lahaina              | 20.9683  | -156.68   | Entire home/apt | 263   | 3              | 66                | 2025-06-26  | 3.12              | 1                              | 297              | 41                    | 430100130084, TA-180-651-4688-01
1435186444432607230 | The Walk-Up- King Terrace Suite w/Sofa Bed+Parking | 699038975 | Summer                        | Honolulu            | Primary Urban Center | 21.2769  | -157.824  | Private room    | 241   | 1              | 0                 | nan         | nan               | 2                              | 351              | 0                     | Exempt
1435876360880444896 | The Walk-Up - King Balcony Suite - No Parking      | 699038975 | Summer                        | Honolulu            | Primary Urban Center | 21.2778  | -157.825  | Private room    | 182   | 1              | 0                 | nan         | nan               | 2                              | 331              | 0                     | Exempt
1435095379143939283 | Maui Ocean Club Kaanapali                          | 699019178 | Roger                         | Maui                | Lahaina              | 20.9163  | -156.697  | Entire home/apt | 426   | 7              | 0                 | nan         | nan               | 1                              | 7                | 0                     | Exempt
1435007729039202921 | Hawaiian Paradise Retreat MT & Ocean Views Private | 698592029 | Lyndsey                       | Honolulu            | Waianae              | 21.4838  | -158.189  | Entire home/apt | 190   | 30             | 0                 | nan         | nan               | 1                              | 268              | 0                     | nan
1431343323472843838 | A Cloud Forest Sanctuary Retreat                   | 698086920 | Diane                         | Hawaii              | North Kona           | 19.7064  | -155.947  | Entire home/apt | 788   | 3              | 0                 | nan         | nan               | 1                              | 151              | 0                     | GE-134-806-4768-01, TA-134-806-4768-01
1431280038827180834 | Luxury Retreat | Lavish Amenities | Kitchenette    | 698065603 | Koloa Landing Resort At Poipu | Kauai               | Koloa-Poipu          | 21.8809  | -159.466  | Private room    | 540   | 1              | 0                 | nan         | nan               | 1                              | 0                | 0                     | Exempt
1430674457182284694 | Tropical Ka'anapali Cottage                        | 697914922 | Brinton                       | Maui                | Lahaina              | 20.9344  | -156.688  | Entire home/apt | 307   | 5              | 0                 | nan         | nan               | 1                              | 252              | 0                     | 2440060060004, TA-194-234-5216-01
1430703871775704065 | Kolea Palace                                       | 697712629 | Robert                        | Hawaii              | South Kohala         | 19.9173  | -155.885  | Entire home/apt | 2744  | 5              | 0                 | nan         | nan               | 2                              | 222              | 0                     | nan
1430729247778516909 | Ainamalu 42                                        | 697712629 | Robert                        | Hawaii              | South Kohala         | 19.9297  | -155.856  | Entire home/apt | 711   | 5              | 0                 | nan         | nan               | 2                              | 364              | 0                     | nan
... (36442 rows omitted)

### Problem 2

In [21]:
# a)
listings.sort("host_id")

id       | name                                               | host_id | host_name | neighbourhood_group | neighbourhood | latitude | longitude | room_type       | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 | number_of_reviews_ltm | license
23188475 | Kapalua Tropical Condo                             | 908     | Sherry    | Maui                | Lahaina       | 21.02    | -156.63   | Private room    | 303   | 7              | 0                 | nan         | nan               | 2                              | 365              | 0                     | 460060330000, TA-207-754-0352-01
26109065 | Seaside Safe Haven Estate Maui                     | 908     | Sherry    | Maui                | Lahaina       | 20.8929  | -156.684  | Entire home/apt | 3000  | 180            | 1                 | 2021-04-04  | 0.02              | 2                              | 364              | 0                     | 245013004000, TA-065-829-2736-01
48941952 | PARADISE AT MAGIC SANDS on Ali'i Drive             | 2971    | Donald    | Hawaii              | North Kona    | 19.593   | -155.969  | Entire home/apt | 300   | 4              | 83                | 2025-03-18  | 1.7               | 1                              | 255              | 17                    | nan
731420   | 60% Off! Romantic Bliss Maui <300 Steps to Beach!  | 7532    | Tracy     | Maui                | Kihei-Makena  | 20.764   | -156.457  | Entire home/apt | 108   | 1              | 527               | 2025-06-14  | 3.43              | 13                             | 355              | 45                    | 390011070070, TA-034-481-9712-01
600944   | 65% Off: TTT#1 of 4 Awarded “Best in Maui” OceanVw | 7532    | Tracy     | Maui                | Kihei-Makena  | 20.764   | -156.457  | Entire home/apt | 128   | 1              | 448               | 2025-04-24  | 2.92              | 13                             | 338              | 41                    | 390011070057, TA-103-948-6976-01
1580775  | 65% Off: TTT#2 of 4  Best in Maui Corner Penthouse | 7532    | Tracy     | Maui                | Kihei-Makena  | 20.764   | -156.457  | Entire home/apt | 152   | 1              | 369               | 2025-06-04  | 2.6               | 13                             | 340              | 46                    | 390011070081, TA-103-948-6976-01
5160612  | 60% Off: Suite Dreams Maui: LessThan300Steps2Beach | 7532    | Tracy     | Maui                | Kihei-Makena  | 20.764   | -156.458  | Entire home/apt | 105   | 1              | 412               | 2025-06-22  | 3.32              | 13                             | 356              | 34                    | 390011070052, TA-178-448-7936-01
5348240  | 65% Off: TTT#3 of 4 Awarded “Best in Maui” OceanVw | 7532    | Tracy     | Maui                | Kihei-Makena  | 20.764   | -156.457  | Entire home/apt | 146   | 1              | 302               | 2025-06-19  | 2.42              | 13                             | 319              | 34                    | 390011070055, TA-103-948-6976-01
23715618 | Mana Kai 608: Oceanfront Remod- Modern Surf Vibe!  | 7532    | Tracy     | Maui                | Kihei-Makena  | 20.7049  | -156.447  | Entire home/apt | 598   | 1              | 187               | 2025-06-10  | 2.12              | 13                             | 29               | 31                    | 390040230064, TA-103-755-0592-01
30052839 | 60% Off Island Surf Studio CarNotNeeded A+Location | 7532    | Tracy     | Maui                | Kihei-Makena  | 20.73    | -156.451  | Entire home/apt | 121   | 1              | 381               | 2025-06-23  | 4.82              | 13                             | 337              | 60                    | 390030010026, TA-142-076-5696-01
... (36442 rows omitted)

In [22]:
# b)
listings.sort("number_of_reviews", descending=True)

id       | name                                           | host_id   | host_name | neighbourhood_group | neighbourhood         | latitude | longitude | room_type       | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 | number_of_reviews_ltm | license
11610598 | The Ohana at Volcanoes National Park           | 31348206  | David     | Hawaii              | Puna                  | 19.4333  | -155.222  | Entire home/apt | 164   | 1              | 1466              | 2025-06-21  | 13.12             | 1                              | 121              | 187                   | TA-173-775-8720-01
2712170  | ‘Elua (2) Just 2 miles from the Kona Airport!  | 13880880  | Katherine | Hawaii              | North Kona            | 19.7222  | -156.016  | Private room    | 100   | 1              | 1444              | 2025-06-22  | 10.65             | 2                              | 230              | 127                   | GE/TA197-922-6112-01
18912777 | #1 Hamoa $125. per night for 2 people          | 131179825 | Rolene    | Maui                | Hana                  | 20.7729  | -156      | Private room    | 108   | 1              | 1281              | 2025-06-25  | 13                | 4                              | 258              | 172                   | 130080150000, TA-123-669-2992-02
18039677 | Sunrise Studio at the Hana Bay B&B             | 123624556 | Kaua      | Maui                | Hana                  | 20.758   | -155.986  | Entire home/apt | 215   | 1              | 1267              | 2025-06-14  | 12.7              | 3                              | 309              | 99                    | 140140170000, TA-014-425-0880-02
18912029 | #2 Keanini  $125. per night for 2 people       | 131179825 | Rolene    | Maui                | Hana                  | 20.7746  | -156.001  | Private room    | 147   | 1              | 1198              | 2025-06-23  | 12.15             | 4                              | 287              | 140                   | 130080150000, TA-123-669-2992-02
8210925  | Kona Town Oasis                                | 43296752  | Marc      | Hawaii              | North Kona            | 19.6411  | -155.989  | Private room    | 106   | 1              | 1178              | 2025-06-11  | 9.88              | 1                              | 41               | 122                   | nan
4069429  | #Private Studio - Waikiki Dream                | 21105755  | Dana      | Honolulu            | Primary Urban Center  | 21.2868  | -157.833  | Entire home/apt | 128   | 1              | 1127              | 2025-06-13  | 8.6               | 1                              | 290              | 103                   | Exempt
2758420  | ‘Ekahi (1) Just 2 miles from the Kona Airport! | 13880880  | Katherine | Hawaii              | North Kona            | 19.7389  | -156.047  | Private room    | 100   | 1              | 1107              | 2025-06-26  | 8.13              | 2                              | 218              | 151                   | GE/TA197-922-6112-01
18075653 | Sunrise Suite at the Hana Bay B&B              | 123624556 | Kaua      | Maui                | Hana                  | 20.7588  | -155.988  | Entire home/apt | 215   | 1              | 1085              | 2025-06-16  | 11.6              | 3                              | 344              | 62                    | 140140170000, TA-014-425-0880-02
2987705  | Kula Treat - Upcountry Maui with Hot Tub!      | 15234735  | Pamela    | Maui                | Makawao-Pukalani-Kula | 20.776   | -156.31   | Entire home/apt | 136   | 1              | 1081              | 2025-06-23  | 8.06              | 2                              | 136              | 114                   | 230220220000, TA-020-811-3664-01
... (36442 rows omitted)

In [ ]:
# c)
students.sort("Name", descending=True)

In [ ]:
# d)
students.sort("Gender")

### Selecting data

In [ ]:
# table_name.column(index_or_label)


# students.column(1)
# students.column("age")

In [ ]:
students.column(0)

In [ ]:
students.row(0)

In [ ]:
students.column(0).item(0)

In [ ]:
students.take(1)

In [ ]:
students.take([0,1,2,3])

In [ ]:
students.take(1).column(1)

### Grouping data

In [ ]:
# table_name.group(column_or_label)


students.group(1)

### Problem 3

In [ ]:
# a)
Age_counts = students.group(1)

In [34]:
Age_counts

Age  | count
17   | 7
18   | 2
19   | 5
20   | 8
21   | 5
22   | 5
23   | 6
24   | 5
25   | 7

In [ ]:
# b)
Age_Gender_counts = students.group([1,2])

In [36]:
Age_Gender_counts

Age  | Gender | count
17   | F      | 3
17   | M      | 4
18   | F      | 2
19   | F      | 2
19   | M      | 3
20   | F      | 5
20   | M      | 3
21   | F      | 3
21   | M      | 2
22   | F      | 4
... (7 rows omitted)

In [ ]:
# c)
Age_pdf = Table() # Create an empty table

Age_pdf = Age_pdf.with_columns(
    "Age", Age_counts.column("Age"),
    "Probability", Age_counts.column("count") / students.num_rows
)

Age_pdf

In [38]:
# b)
# 0.10 + 0.16 + 0.10 = 0.36

In [39]:
# e)
# 1- 0.14 - 0.04 = 0.82